"use client"
import { useEffect, useState } from "react"
import { Button } from "@/components/ui/button"
import { Checkbox } from "@/components/ui/checkbox"
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select"
import { Textarea } from "@/components/ui/textarea"

export interface CohortEditFormValues { cohortName:string; description:string; courseCode:string; semester:string; year:string; maxStudents:string; autoApprove:boolean; allowSelfEnrollment:boolean; isActive:boolean }
const empty:CohortEditFormValues={cohortName:"",description:"",courseCode:"",semester:"",year:"",maxStudents:"",autoApprove:true,allowSelfEnrollment:false,isActive:true}
export default function CohortEditModal({isOpen,cohortDetails,onClose,onSubmit,isSubmitting=false}:{isOpen:boolean;cohortDetails:any|null;onClose:()=>void;onSubmit:(values:CohortEditFormValues)=>Promise<void>|void;isSubmitting?:boolean}){
 const [form,setForm]=useState(empty);useEffect(()=>{if(isOpen&&cohortDetails)setForm({cohortName:cohortDetails.title||"",description:cohortDetails.description||"",courseCode:cohortDetails.course_code||"",semester:cohortDetails.semester||"",year:cohortDetails.year?String(cohortDetails.year):"",maxStudents:cohortDetails.max_students?String(cohortDetails.max_students):"",autoApprove:cohortDetails.auto_approve??true,allowSelfEnrollment:cohortDetails.allow_self_enrollment??false,isActive:cohortDetails.is_active??true});else if(!isOpen)setForm(empty)},[isOpen,cohortDetails]);const set=(key:keyof CohortEditFormValues,value:string|boolean)=>setForm(prev=>({...prev,[key]:value}));
 return <Dialog open={isOpen} onOpenChange={open=>!open&&onClose()}><DialogContent className="max-h-[90vh] overflow-y-auto sm:max-w-xl"><DialogHeader><DialogTitle>Edit cohort</DialogTitle><DialogDescription>Update cohort information, enrollment rules, and lifecycle.</DialogDescription></DialogHeader><div className="grid gap-4"><Field id="edit-cohort-name" label="Cohort name"><Input id="edit-cohort-name" value={form.cohortName} onChange={e=>set("cohortName",e.target.value)}/></Field><Field id="edit-cohort-description" label="Description"><Textarea id="edit-cohort-description" value={form.description} onChange={e=>set("description",e.target.value)}/></Field><div className="grid gap-4 sm:grid-cols-2"><Field id="edit-course-code" label="Course code"><Input id="edit-course-code" value={form.courseCode} onChange={e=>set("courseCode",e.target.value)}/></Field><Field id="edit-max-students" label="Maximum students"><Input id="edit-max-students" type="number" min="1" value={form.maxStudents} onChange={e=>set("maxStudents",e.target.value)}/></Field><Field id="edit-semester" label="Semester"><Select value={form.semester} onValueChange={v=>set("semester",v)}><SelectTrigger id="edit-semester"><SelectValue placeholder="Select semester"/></SelectTrigger><SelectContent>{["Spring","Summer","Fall","Winter"].map(v=><SelectItem key={v} value={v}>{v}</SelectItem>)}</SelectContent></Select></Field><Field id="edit-year" label="Year"><Input id="edit-year" type="number" value={form.year} onChange={e=>set("year",e.target.value)}/></Field></div><label htmlFor="edit-auto-approve" className="flex items-center gap-3 rounded-xl border p-3 text-sm"><Checkbox id="edit-auto-approve" checked={form.autoApprove} onCheckedChange={v=>set("autoApprove",Boolean(v))}/>Auto-approve enrollments</label><label htmlFor="edit-self-enrollment" className="flex items-center gap-3 rounded-xl border p-3 text-sm"><Checkbox id="edit-self-enrollment" checked={form.allowSelfEnrollment} onCheckedChange={v=>set("allowSelfEnrollment",Boolean(v))}/>Allow self-enrollment</label><Field id="edit-lifecycle" label="Lifecycle"><Select value={form.isActive?"active":"inactive"} onValueChange={v=>set("isActive",v==="active")}><SelectTrigger id="edit-lifecycle"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="active">Active</SelectItem><SelectItem value="inactive">Inactive</SelectItem></SelectContent></Select></Field></div><DialogFooter><Button variant="outline" onClick={onClose}>Cancel</Button><Button disabled={isSubmitting||!form.cohortName.trim()} onClick={()=>onSubmit(form)}>{isSubmitting?"Saving…":"Save changes"}</Button></DialogFooter></DialogContent></Dialog>
}
function Field({id,label,children}:{id:string;label:string;children:React.ReactNode}){return <div className="space-y-2"><Label htmlFor={id}>{label}</Label>{children}</div>}
